import React from "react";
import Head from "next/head";

const HtmlHead = ({ currentPage }) => {
	return (
		<Head>
			<title>Bridge Index Token| {currentPage} </title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/images/logo.svg" />
			<link rel="preconnect" href="https://fonts.googleapis.com" />
			<link
				rel="preconnect"
				href="https://fonts.gstatic.com"
				crossOrigin
			/>
			<link
				href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
				rel="stylesheet"
			/>
			<link
				href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap"
				rel="stylesheet"
			/>
		</Head>
	);
};

export default HtmlHead;
